### PR TITLE
Added [ElementsCreateOptions] to StripeCard

### PR DESCRIPTION
**Pull request by va2ron1**
A new prop named **elementsOptions** has been added of type ElementsCreateOptions.
**Note**: The bundles files don't have the changes.

### CODE REVIEW

**Comment by AckerApple** [comment]
Do you have any documentation or links indicating difference between these two?


- options: stripe.elements.ElementsOptions;
- elementsOptions: stripe.elements.ElementsCreateOptions;


Maybe add it to README?

**Comment by AckerApple** [comment]
Maybe rename to createOptions?

**Comment by va2ron1** [comment]
Yes, there's one in the Stripe API Documentation.
1. ElementsCreateOptions - https://stripe.com/docs/js/elements_object/create
2. ElementsOptions  - https://stripe.com/docs/js/elements_object/create_element?type=card

Basically the first is the options for the _Elements_ instance in which you can set custom fonts or set a fixed language. And the second, in this case, are the options for the card element (style, classes, value, ...).

Navigating on the web a found this that can be helpful for future additions or implementations:
- https://pub.dev/documentation/stripe_js/latest/lib.src.stripe/ElementsCreateOptions-class.html
 
Note: I will rename it to _createOptions_, I didn't think it this way.

**Comment by selected-pixel-jameson** [comment]
Can we get this merged and released? This is a huge piece of necessary functionality.

**Comment by AckerApple** [comment]
I forgot about this and have been swamped. @selected-pixel-jameson if you will validate and provide some valuable feedback, I will attempt to escalate review and merge

**Comment by AckerApple** [comment]
This has been merged

@selected-pixel-jameson this was not huge missing functionality, look at the files changed. It was just docs and a data typing

**Comment by AckerApple** [comment]
Ah I found #49

**Pull request merged**
