### PR TITLE
Adding support for creating sources

### PR DESCRIPTION
**Pull request by rogerb87**
This pull-requests allow to create sources (store credit card information) and provides the available to charge them multiple times instead of tokens.

Please feel free to change anything you want. Let me know if I missed something.

Best regards
Roger

### CODE REVIEW

**Comment by AckerApple** [comment]
Could you give me a link to include in the readme to read more about sources for Stripe.

You can put in readme or I’ll get it in.

Hey, a very soulful thank you for this pull request. You should have a friendly face github icon to go with that friendly participation you’re giving to open source. I like to have a face to go with the people I work with

**Comment by rogerb87** [comment]
Hey AckerApple,

thank you for your quick response. I'll definitely change my icon, but as you may notice I don't contribute as much as I should.

Anyway, here is the link for the stripe documentation. As far as I remember, You will need create a source for charging credit cards later.

[https://stripe.com/docs/sources](https://stripe.com/docs/sources)

Best regards
Roger

**Comment by AckerApple** [comment]
I spent way too much time on getting this to work. It does not work.

Please use the demo to set your own api key and then test the createSource:
https://ackerapple.github.io/stripe-angular/

I just keep getting the error seen here:
image

**Comment by AckerApple** [comment]
Based on the error, I think it wants me to capture name and address info?

What do you think?

**Comment by rogerb87** [comment]
Wow, I'm sorry that you had so much trouble with this. You need to clear the extraData field.

**Comment by AckerApple** [comment]
Ok, I will attempt to test again tomorrow by not sending and extra data. That sounds easier said than done but I could be wrong.

I was hoping you could test the new code on your own version to just at least tell me if it works from your end (outside of the demo, using your own code).

I will report tomorrow. Thank you again

**Comment by rogerb87** [comment]
Hi there,

I've just installed the newest version of this library and everything works fine for me. 

At this point I would like to thank you very much for this awesome library. It took me only a couple minutes to get stripe working in my Angular project with this (btw. well documented) code :-)

Best regards
Roger

**Comment by AckerApple** [comment]
Alright that's extra great and well timed as I have been working real extra hard.

I did find that removing extraData, enabled transmission and then received a Stripe source. Success!

So, I spent some more time studying Stripe source, especially when trying to make work with bank data. It seems it will not work with my existing stripe-bank component. I removed any association of stripe-bank with stripe-source. However in the future, I did find Stripe does have idealBank and iban elements that are both bank related and work as compatible elements with Stripe source. For now, I'm not going to worry about bank data as a Stripe source until someone wants it.

I need your help to finish this ticket off. I released version 4.0.2 to github ONLY. Please ensure it still work for you and let me know before I publish to npm. I tested in my demo area and all checks out. The removal of extra data kind of baffles me but if it works for you still, I will release and we can then close this ticket

**Comment by rogerb87** [comment]
Hi there,

sorry for the delayed response. I've checked this now. For me everything works just like expected. 

I guess mistyped yourself in this request because it should be version 0.4.2 instead of 4.0.2. 

Best regards
Roger

**Pull request merged**
