### PR TITLE
Simplify Module Initialization

### LINKED ISSUE #22: Feature Request: Simplify Module Initialization
First off I would like to thank you for all your hard word on making this project. I have been looking for a Stripe solution for Angular for a while and this has come by far the closest to what I wanted.

It does seem like getting Stripe to work is a little bit tricky due to having to rely on Stipe Elements and the API it exposes thus making the setup cumbersome in a framework like Angular where if we had direct access to APIs it would make the process a lot easier on us.

That being said you have gotten by far the closest. I have one simple request to clean up my code a bit. That would be:
1) Export directly as `StripeModule` rather then `Module` so I don't have to rename the import.
2) Take in an option for the `publishable key` for the `forRoot()` initialization so I don't have to add `setPublishableKey()` to my App component.

Example of request:
`app.module.ts`
```ts
...
import { StripeModule } from 'stripe-angular';

@NgModule({
  imports: [StripeModule.forRoot(environment.stripe.pk), ...]
  ...
})
export class AppModule {}
```

These may seem like small things however I think it is small things like that that really make some libraries stand apart from others.

These changes don't have to replace the existing exports, that way not to be an immediate breaking change but instead could be added in then the old export of `Module` could be deprecated and removed later down the road similar to what Angular core does with deprecated APIs on major releases.

Beyond this my only other complaint would be having to use the options in order to apply CSS, however I know that isn't on you but instead on how Stripe has exposed their APIs to us.

Thank you so much for your time and hard work! I look forward to seeing how this Library progresses in 2020

### PR DESCRIPTION
**Pull request by wSedlacek**
Fixes #22

### CODE REVIEW

**Comment by wSedlacek** [comment]
@gmfun  I attempted to follow your styling as close as possible.
I attempted to limit the number of breaking changes to as few as possible.
I ran the test and have that working but was not familiar with the `build`, `start` or `compile` commands setup in this project to test if these changes actually work.

Let me know what you think and what further steps need to be taken to merge this.

**Comment by AckerApple** [comment]
Please change the major version number on these breaking changes.

I may accept this but it would require people to upgrade a lot

**Comment by wSedlacek** [comment]
Updated Major Version.

While this does depreciate using `Module` and updates the documentation to have users use `.forRoot()` for their key, I have attempted to be careful not to break the current init process using optional variables.

Is there somewhere I missed that would cause this to break any current installs?

**Comment by AckerApple** [comment]
The Module is the breaking change. It also helps me because I'm going to review other pull requests AND most likely run the bundling code using latest Angular hopefully with Ivy compat.

I will be in touch

**Comment by wSedlacek** [comment]
Alright! Well keep me posted!

**Comment by AckerApple** [comment]
I just built another one of my packages, angular-file, using Angular 9 with Ivy enabled in the demo.

This other Angular package of mine wants my attention, as seen here: https://github.com/AckerApple/agm-overlays/issues/39

So I'm still tied up but will get to your pull request in time.

Thank you kindly.

**Comment by AckerApple** [comment]
Great code. Thank you much. Version 1.0.0 has been released and it was bundled using Angular 9

**Pull request merged**
