### PR TITLE
Minor change to make argument optional

### PR DESCRIPTION
**Pull request by SudharakaP**
This is the fix for https://github.com/AckerApple/stripe-angular/issues/9. The case where the argument is undefined should be taken into account.

### CODE REVIEW

**Comment by AckerApple** [comment]
Please make this change in the src folder. The dist folder gets over written on build

**Comment by SudharakaP** [comment]
@AckerApple : Sorry; I was more interested in fixing my problem that I overlooked it. Thanks :)

**Comment by AckerApple** [comment]
Ok, I see how that shuts TypeScript. I’ll accept.

Consider this though, I think a more proper data typing would be better that matches the data typing of what Stripe is asking for. However, this is why I love TypeScript and loosely typed languages because we can move forward and choose ourselves how anal about details to be.

Good show. It’ll be Monday for me to publish this to NPM but for now I’ll merge from my iPad.

**Comment by SudharakaP** [comment]
Wonderful. Maybe when I have some more free time I'll do a proper data
typing but for now I think this gets rid of the bug. Cheers. 😀

**Comment by AckerApple** [comment]
released to npm stripe-angular@0.5.0

**Pull request merged**
